//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AntiCustomerServiceSystem.Models
{
    public partial class Company
    {
        public Company()
        {
            this.Issues = new HashSet<Issue>();
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MainPhone { get; set; }
        public string Account { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
    
}
