//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AntiCustomerServiceSystem.Models
{
    public partial class FollowUp
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string Action { get; set; }
        public string State { get; set; }
        public Nullable<short> Outcome { get; set; }
        public Nullable<short> Timeliness { get; set; }
    
        public virtual Call Call { get; set; }
    }
    
}
