//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ServiceBlazerMVC4.Models
{
    public partial class ServiceSystemContainer : DbContext
    {
        public ServiceSystemContainer()
            : base("name=ServiceSystemContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Companies { get; set; }
        public DbSet<Issue> Issues { get; set; }
        public DbSet<Call> Calls { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<FollowUp> FollowUps { get; set; }
    }
}
